### PR TITLE
Add athena book

### PR DESCRIPTION
**Pull request by hasanza**
Adds the Athena Book.

### CODE REVIEW

**Comment by lrettig** [comment]
@hasanza I assumed you'd create the book here by cloning https://github.com/succinctlabs/sp1/tree/main/book, but this looks very different from that. I added some scripts to lint and build the book but they're not working. What did you use as your starting point here?

**Comment by hasanza** [comment]
@lrettig I created a book from scratch using `mdbook`. I thought that would be better and we could bring in material as needed.

**Comment by hasanza** [comment]
@lrettig I investigated the workflow file and it appears that the directory in which the linting, building, and archiving workflows are run is the repository root. I fixed this by adding the correct working directory for the work flows and now everything appears to work properly.

**Comment by hasanza** [comment]
Removed the build folder and added it to git ignore in latest commit.

**Pull request merged**
